INSERT INTO ASSET_TYPE (NAME) VALUES ('Equipment');
INSERT INTO ASSET_TYPE (NAME) VALUES ('Electronics');
INSERT INTO ASSET_TYPE (NAME) VALUES ('Books');
INSERT INTO ASSET_TYPE (NAME) VALUES ('Machinery');


